-- =============================================================================
-- Migration: 001_initial_schema
-- Project:   Ferma.Tolk
-- Ticket:    FT-004
-- Created:   2026-04-05
-- =============================================================================
-- Schema for all user data currently stored in localStorage.
-- See docs/LOCALSTORAGE-INVENTORY.md for the full migration map.
--
-- Conventions:
--   - All primary keys are UUIDs generated by gen_random_uuid().
--   - All timestamps are TIMESTAMPTZ (UTC-aware).
--   - Soft-deletes are used where data retention is important (transactions).
--   - Row-Level Security (RLS) is enabled on every user-data table.
--   - All RLS policies use auth.uid() — Supabase Auth built-in.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "pgcrypto";   -- gen_random_uuid(), crypt()
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";  -- query performance monitoring

-- ---------------------------------------------------------------------------
-- 1. users
-- ---------------------------------------------------------------------------
-- Extends Supabase Auth (auth.users). We do NOT store passwords here — that
-- is handled entirely by Supabase Auth (bcrypt server-side).
-- This table holds application-level profile data only.
--
-- BLOCKER-01 / BLOCKER-02 (SECURITY-BASELINE.md): passwords live in
-- auth.users.encrypted_password, managed by GoTrue. Never in this table.
-- ---------------------------------------------------------------------------
CREATE TABLE public.users (
    id              UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email           TEXT UNIQUE NOT NULL,
    security_hint   TEXT,                        -- hint for password-reset question (non-secret)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.users IS
    'Application profile data. Credentials are managed exclusively by Supabase Auth.';

-- Trigger: keep updated_at current
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER users_updated_at
    BEFORE UPDATE ON public.users
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users: read own profile"
    ON public.users FOR SELECT
    USING (auth.uid() = id);

CREATE POLICY "users: update own profile"
    ON public.users FOR UPDATE
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);

-- Auto-create profile row when a new auth user registers
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
    INSERT INTO public.users (id, email, security_hint)
    VALUES (
        NEW.id,
        NEW.email,
        (NEW.raw_user_meta_data->>'security_hint')
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ---------------------------------------------------------------------------
-- 2. projects
-- ---------------------------------------------------------------------------
-- Maps to agri_projects_{userId} in localStorage.
-- Crops / farm units a user manages (e.g. "Onion Field", "Greenhouse").
-- ---------------------------------------------------------------------------
CREATE TABLE public.projects (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    slug        TEXT NOT NULL,           -- machine-readable id (e.g. 'onion', 'all_projects')
    label       TEXT NOT NULL,           -- display name (e.g. 'Onion Field')
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, slug)
);

COMMENT ON TABLE public.projects IS
    'Farm projects / crop units. Migrated from agri_projects_{userId} localStorage key.';

-- RLS
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "projects: full access to own rows"
    ON public.projects FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 3. transactions
-- ---------------------------------------------------------------------------
-- Maps to agri_transactions_{userId} in localStorage.
-- Core financial records: income and expense entries.
-- ---------------------------------------------------------------------------
CREATE TABLE public.transactions (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    project_id      UUID REFERENCES public.projects(id) ON DELETE SET NULL,
    type            TEXT NOT NULL CHECK (type IN ('income', 'expense')),
    category        TEXT NOT NULL,           -- 'opex' | 'capex' | 'operationalRevenue' | etc.
    sub_category    TEXT,                    -- 'fuel' | 'salary' | 'seeds' | etc.
    amount          NUMERIC(14, 2) NOT NULL CHECK (amount >= 0),
    liters          NUMERIC(10, 3),          -- fuel volume
    fuel_type       TEXT,                    -- 'petrol' | 'diesel' | 'propan' | 'other'
    is_fuel         BOOLEAN NOT NULL DEFAULT FALSE,
    description     TEXT,
    entry_date      TIMESTAMPTZ NOT NULL,    -- the date the transaction occurred (user-supplied)
    deleted_at      TIMESTAMPTZ,             -- soft-delete; NULL = active
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.transactions IS
    'Farm income and expense records. Migrated from agri_transactions_{userId} localStorage key.';

CREATE INDEX idx_transactions_user_date
    ON public.transactions (user_id, entry_date DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_transactions_project
    ON public.transactions (project_id)
    WHERE deleted_at IS NULL;

CREATE TRIGGER transactions_updated_at
    BEFORE UPDATE ON public.transactions
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- RLS
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "transactions: full access to own rows"
    ON public.transactions FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 4. description_mappings
-- ---------------------------------------------------------------------------
-- Maps to agri_desc_mappings_{userId} in localStorage.
-- User-trained classification: free-text description → OPEX sub-category ID.
-- ---------------------------------------------------------------------------
CREATE TABLE public.description_mappings (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    description_key TEXT NOT NULL,       -- lowercased transaction description
    sub_category_id TEXT NOT NULL,       -- e.g. 'fuel', 'salary', 'seeds'
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, description_key)
);

COMMENT ON TABLE public.description_mappings IS
    'User-trained description→category mappings. Migrated from agri_desc_mappings_{userId}.';

CREATE TRIGGER description_mappings_updated_at
    BEFORE UPDATE ON public.description_mappings
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- RLS
ALTER TABLE public.description_mappings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "description_mappings: full access to own rows"
    ON public.description_mappings FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 5. forecast_adjustments
-- ---------------------------------------------------------------------------
-- Maps to agri_forecast_adjustments_{userId} in localStorage.
-- Manual budget delta adjustments per OPEX category per month.
-- ---------------------------------------------------------------------------
CREATE TABLE public.forecast_adjustments (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    year            SMALLINT NOT NULL CHECK (year >= 2020 AND year <= 2100),
    month           SMALLINT NOT NULL CHECK (month >= 0 AND month <= 11),  -- JS 0-indexed
    category_id     TEXT NOT NULL,
    delta           NUMERIC(14, 2) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, year, month, category_id)
);

COMMENT ON TABLE public.forecast_adjustments IS
    'Manual forecast adjustments per category per month. Migrated from agri_forecast_adjustments_{userId}.';

CREATE TRIGGER forecast_adjustments_updated_at
    BEFORE UPDATE ON public.forecast_adjustments
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- RLS
ALTER TABLE public.forecast_adjustments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "forecast_adjustments: full access to own rows"
    ON public.forecast_adjustments FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 6. chat_messages
-- ---------------------------------------------------------------------------
-- Maps to agri_chat_history_{userId} in localStorage.
-- Persistent chat assistant history.
-- ---------------------------------------------------------------------------
CREATE TABLE public.chat_messages (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    role        TEXT NOT NULL CHECK (role IN ('user', 'bot')),
    content     TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.chat_messages IS
    'Chat assistant message history. Migrated from agri_chat_history_{userId}.';

CREATE INDEX idx_chat_messages_user_created
    ON public.chat_messages (user_id, created_at DESC);

-- RLS
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "chat_messages: full access to own rows"
    ON public.chat_messages FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Grants: allow the authenticated role to use all tables
-- (anon role gets nothing — enforced by RLS)
-- ---------------------------------------------------------------------------
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO authenticated;
